[build]
builder = "DOCKERFILE"

[deploy]
# Healthcheck désactivé temporairement pour voir les logs d'erreur
# healthcheckPath = "/health"
# healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
