import { UserRole } from './roles.guard';

export enum UserProfile {
  EXPERT_COMPTABLE = 'expert_comptable',
  ENTREPRENEUR = 'entrepreneur', 
  BANQUE = 'banque',
  ADMINISTRATION_FISCAL = 'administration_fiscal',
  HR_MANAGER = 'hr_manager',
  ACCOUNTANT = 'accountant',
  MANAGER = 'manager',
  EMPLOYEE = 'employee',
  ADMIN = 'admin'
}

// Définition des modules par profil avec typage explicite
const ALL_MODULES_EXCEPT_ADMIN = [
  'accounting.dashboard',
  'accounting.chart-of-accounts',
  'accounting.journal',
  'accounting.trial-balance',
  'accounting.profit-loss',
  'accounting.balance-sheet',
  'accounting.aged-balance',
  'accounting.vat',
  'accounting.closure',
  'accounting.bank',
  'accounting.automation',
  'tax.vat-declarations',
  'tax.corporate-tax',
  'tax.annual-returns',
  'tax.audit-logs',
  'collections.customer-dunning',
  'collections.supplier-dunning',
  'collections.letters',
  'collections.reports',
  'expert.dashboard',
  'expert.client-portfolio',
  'expert.mission-tracking',
  'expert.invoicing',
  'expert.document-management',
  'dashboard.overview',
  'entrepreneur.dashboard',
  'treasury.overview',
  'treasury.forecast',
  'treasury.alerts',
  'formalization.nif',
  'employees.list',
  'employees.timesheets',
  'employees.leave',
  'employees.payroll',
  'employees.transfers',
  'employees.documents',
  'entrepreneur.financial-summary',
  'entrepreneur.compliance-status',
  'banking.transactions',
  'banking.reconciliation',
  'banking.transfers',
  'banking.statement-import',
  'hr.dashboard',
  'hr.employees',
  'hr.timesheets',
  'hr.leave-management',
  'hr.payroll',
  'hr.transfers',
  'hr.documents',
  'hr.analytics',
  'hr.recruitment',
  'hr.performance',
  'hr.training',
  'hr.compliance',
  'manager.dashboard',
  'manager.team',
  'manager.timesheets',
  'manager.leave-approval',
  'manager.team-analytics',
  'manager.reports',
  'manager.performance',
  'manager.budget',
  'manager.projects',
  'employee.profile',
  'employee.timesheets',
  'employee.leave-requests',
  'employee.payslips',
  'employee.documents',
  // 🆕 Modules IA/ML existants
  'ai.document-analysis',
  'ai.anomaly-detection',
  'ai.financial-predictions',
  'ai.rag-search',
  'ai.cash-flow-predictions',
  'ai.business-insights',
  'ai.risk-assessment',
  'ai.talent-analytics',
  'ai.recruitment-scoring',
  'ai.performance-prediction',
  'ai.team-productivity',
  'ai.project-forecasting',
  'ai.decision-support',
  // 🆕 Modules Notifications existants
  'notifications.email',
  'notifications.sms',
  'notifications.real-time',
  'notifications.alerts',
  'notifications.reports',
  'notifications.hr-alerts',
  'notifications.team-alerts',
  'notifications.in-app',
  'notifications.preferences',
  'notifications.history',
  // 🆕 Modules CRM & Marketing existants
  'crm.client-portfolio',
  'crm.campaign-management',
  'crm.lead-scoring',
  'crm.lead-generation',
  'crm.email-marketing',
  'crm.employee-engagement',
  'crm.team-management',
  'crm.contacts',
  'crm.activities',
  'crm.opportunities',
  // 🆕 Modules Automation existants
  'automation.workflows',
  'automation.schedules',
  'automation.integrations',
  'automation.reports',
  'automation.hr-workflows',
  // 🆕 Modules Banking & Fintech existants
  'banking.api-connections',
  'banking.auto-reconciliation',
  'banking.anomaly-detection',
  'banking.credit-scoring',
  'banking.provider-management',
  // 🆕 Modules Treasury avancés existants
  'treasury.cash-flow-forecast',
  'treasury.sepa-direct-debit',
  'treasury.bills-of-exchange',
  'treasury.runway-analysis',
  'treasury.alerts-config',
  // 🆕 Modules Reporting & Analytics
  'reporting.custom-dashboards',
  'reporting.financial-ratios',
  'reporting.business-intelligence',
  'reporting.export-tools',
  'reporting.audit-trails'
];

const PROFILE_MODULES_BASE: Record<UserProfile, string[]> = {
  [UserProfile.EXPERT_COMPTABLE]: [
    'accounting.dashboard',
    'accounting.chart-of-accounts',
    'accounting.journal',
    'accounting.trial-balance',
    'accounting.profit-loss',
    'accounting.balance-sheet',
    'accounting.aged-balance',
    'accounting.vat',
    'accounting.closure',
    'accounting.bank',
    'accounting.automation',
    'tax.vat-declarations',
    'tax.corporate-tax',
    'tax.annual-returns',
    'tax.audit-logs',
    'collections.customer-dunning',
    'collections.supplier-dunning',
    'collections.letters',
    'collections.reports',
    'expert.dashboard',
    'expert.client-portfolio',
    'expert.mission-tracking',
    'expert.invoicing',
    'expert.document-management',
    // 🆕 IA/ML avancé pour Expert Comptable
    'ai.document-analysis',
    'ai.anomaly-detection',
    'ai.financial-predictions',
    'ai.rag-search',
    'ai.business-insights',
    'ai.risk-assessment',
    // 🆕 Notifications professionnelles
    'notifications.email',
    'notifications.sms',
    'notifications.real-time',
    'notifications.alerts',
    'notifications.reports',
    'notifications.in-app',
    'notifications.preferences',
    'notifications.history',
    // 🆕 CRM & Reporting avancé
    'crm.client-portfolio',
    'crm.campaign-management',
    'crm.lead-scoring',
    'crm.activities',
    'crm.opportunities',
    // 🆕 Automation & Productivité
    'automation.workflows',
    'automation.schedules',
    'automation.integrations',
    'automation.reports',
    // 🆕 Banking & Fintech
    'banking.api-connections',
    'banking.auto-reconciliation',
    'banking.anomaly-detection',
    'banking.credit-scoring',
    'banking.provider-management',
    // 🆕 Reporting & Analytics
    'reporting.custom-dashboards',
    'reporting.financial-ratios',
    'reporting.business-intelligence',
    'reporting.export-tools',
    'reporting.audit-trails'
  ],
  [UserProfile.ENTREPRENEUR]: [
    'dashboard.overview',
    'entrepreneur.dashboard',
    'treasury.overview',
    'treasury.forecast',
    'treasury.alerts',
    'formalization.nif',
    'employees.list',
    'employees.timesheets',
    'employees.leave',
    'employees.payroll',
    'employees.transfers',
    'employees.documents',
    'entrepreneur.financial-summary',
    'entrepreneur.compliance-status',
    // 🆕 IA Décisionnelle pour Entrepreneur
    'ai.cash-flow-predictions',
    'ai.business-insights',
    'ai.risk-assessment',
    'ai.financial-predictions',
    'ai.decision-support',
    // 🆕 Notifications Stratégiques
    'notifications.email',
    'notifications.sms',
    'notifications.real-time',
    'notifications.alerts',
    'notifications.reports',
    'notifications.in-app',
    'notifications.preferences',
    'notifications.history',
    // 🆕 Marketing & CRM
    'crm.lead-generation',
    'crm.email-marketing',
    'crm.lead-scoring',
    'crm.contacts',
    'crm.activities',
    // 🆕 Automation Business
    'automation.workflows',
    'automation.schedules',
    'automation.integrations',
    'automation.reports',
    // 🆕 Banking & Treasury avancé
    'banking.api-connections',
    'banking.auto-reconciliation',
    'banking.anomaly-detection',
    'banking.provider-management',
    'treasury.cash-flow-forecast',
    'treasury.sepa-direct-debit',
    'treasury.bills-of-exchange',
    'treasury.runway-analysis',
    'treasury.alerts-config',
    // 🆕 Reporting Business
    'reporting.custom-dashboards',
    'reporting.financial-ratios',
    'reporting.business-intelligence',
    'reporting.export-tools',
    'reporting.audit-trails'
  ],
  [UserProfile.BANQUE]: [
    'banking.transactions',
    'banking.reconciliation',
    'banking.transfers',
    'banking.statement-import'
  ],
  [UserProfile.ADMINISTRATION_FISCAL]: [
    'tax.vat-declarations',
    'tax.corporate-tax',
    'tax.annual-returns',
    'tax.audit-logs'
  ],
  [UserProfile.HR_MANAGER]: [
    'hr.dashboard',
    'hr.employees',
    'hr.timesheets',
    'hr.leave-management',
    'hr.payroll',
    'hr.transfers',
    'hr.documents',
    'hr.analytics',
    'hr.recruitment',
    'hr.performance',
    'hr.training',
    'hr.compliance',
    // 🆕 IA RH pour Manager
    'ai.talent-analytics',
    'ai.recruitment-scoring',
    'ai.performance-prediction',
    'ai.team-productivity',
    'ai.business-insights',
    // 🆕 Notifications RH
    'notifications.email',
    'notifications.sms',
    'notifications.real-time',
    'notifications.hr-alerts',
    'notifications.reports',
    'notifications.in-app',
    'notifications.preferences',
    'notifications.history',
    // 🆕 CRM RH & Engagement
    'crm.employee-engagement',
    'crm.team-management',
    'crm.contacts',
    'crm.activities',
    // 🆕 Automation RH
    'automation.hr-workflows',
    'automation.schedules',
    'automation.integrations',
    'automation.reports',
    // 🆕 Banking & Paie
    'banking.api-connections',
    'banking.auto-reconciliation',
    'banking.provider-management',
    'treasury.sepa-direct-debit',
    'treasury.alerts-config',
    // 🆕 Reporting RH
    'reporting.custom-dashboards',
    'reporting.financial-ratios',
    'reporting.business-intelligence',
    'reporting.export-tools',
    'reporting.audit-trails'
  ],
  [UserProfile.ACCOUNTANT]: [
    'accounting.dashboard',
    'accounting.chart-of-accounts',
    'accounting.journal',
    'accounting.trial-balance',
    'accounting.profit-loss',
    'accounting.balance-sheet',
    'accounting.vat',
    'accounting.bank',
    'accounting.reports'
  ],
  [UserProfile.MANAGER]: [
    'manager.dashboard',
    'manager.team',
    'manager.timesheets',
    'manager.leave-approval',
    'manager.team-analytics',
    'manager.reports',
    'manager.performance',
    'manager.budget',
    'manager.projects',
    // 🆕 IA Management
    'ai.team-productivity',
    'ai.project-forecasting',
    'ai.decision-support',
    'ai.performance-prediction',
    'ai.business-insights',
    // 🆕 Notifications Management
    'notifications.email',
    'notifications.sms',
    'notifications.real-time',
    'notifications.team-alerts',
    'notifications.reports',
    'notifications.in-app',
    'notifications.preferences',
    'notifications.history',
    // 🆕 CRM Management d'équipe
    'crm.team-management',
    'crm.contacts',
    'crm.activities',
    'crm.opportunities',
    // 🆕 Automation Management
    'automation.workflows',
    'automation.schedules',
    'automation.integrations',
    'automation.reports',
    // 🆕 Banking & Budget
    'banking.api-connections',
    'banking.auto-reconciliation',
    'banking.provider-management',
    'treasury.cash-flow-forecast',
    'treasury.alerts-config',
    // 🆕 Reporting Management
    'reporting.custom-dashboards',
    'reporting.financial-ratios',
    'reporting.business-intelligence',
    'reporting.export-tools',
    'reporting.audit-trails'
  ],
  [UserProfile.EMPLOYEE]: [
    'employee.profile',
    'employee.timesheets',
    'employee.leave-requests',
    'employee.payslips',
    'employee.documents',
    // 🆕 Notifications Employé
    'notifications.email',
    'notifications.sms',
    'notifications.real-time',
    'notifications.in-app',
    'notifications.preferences',
    'notifications.history',
    // 🆕 CRM Employé (limité)
    'crm.contacts',
    'crm.activities',
    // 🆕 Reporting Employé (limité)
    'reporting.export-tools'
  ],
  [UserProfile.ADMIN]: ALL_MODULES_EXCEPT_ADMIN
};

export const PROFILE_MODULES: Record<UserProfile, string[]> = PROFILE_MODULES_BASE;

export const PORTAL_ROUTES: Record<UserProfile, string> = {
  [UserProfile.EXPERT_COMPTABLE]: '/expert-comptable',
  [UserProfile.ENTREPRENEUR]: '/entrepreneur',
  [UserProfile.BANQUE]: '/banque',
  [UserProfile.ADMINISTRATION_FISCAL]: '/fiscal',
  [UserProfile.HR_MANAGER]: '/hr',
  [UserProfile.ACCOUNTANT]: '/accounting',
  [UserProfile.MANAGER]: '/manager',
  [UserProfile.EMPLOYEE]: '/employee',
  [UserProfile.ADMIN]: '/admin'
};

export const getPortalByRole = (role: UserRole): string => {
  const roleToPortal: Record<UserRole, string> = {
    [UserRole.ADMIN]: PORTAL_ROUTES[UserProfile.ADMIN],
    [UserRole.TAX_ADMIN]: PORTAL_ROUTES[UserProfile.ADMINISTRATION_FISCAL],
    [UserRole.HR_MANAGER]: PORTAL_ROUTES[UserProfile.HR_MANAGER],
    [UserRole.ACCOUNTANT]: PORTAL_ROUTES[UserProfile.ACCOUNTANT],
    [UserRole.MANAGER]: PORTAL_ROUTES[UserProfile.MANAGER],
    [UserRole.EMPLOYEE]: PORTAL_ROUTES[UserProfile.EMPLOYEE],
    [UserRole.USER]: PORTAL_ROUTES[UserProfile.ENTREPRENEUR], // Default
    [UserRole.EXPERT_COMPTABLE]: PORTAL_ROUTES[UserProfile.EXPERT_COMPTABLE], // ✅ AJOUTER
    [UserRole.BANQUE]: PORTAL_ROUTES[UserProfile.BANQUE], // ✅ AJOUTER
  };
  
  return roleToPortal[role] || PORTAL_ROUTES[UserProfile.ENTREPRENEUR];
};

export const getModulesByRole = (role: UserRole): string[] => {
  const roleToProfile: Record<UserRole, UserProfile> = {
    [UserRole.ADMIN]: UserProfile.ADMIN,
    [UserRole.TAX_ADMIN]: UserProfile.ADMINISTRATION_FISCAL,
    [UserRole.HR_MANAGER]: UserProfile.HR_MANAGER,
    [UserRole.ACCOUNTANT]: UserProfile.ACCOUNTANT,
    [UserRole.MANAGER]: UserProfile.MANAGER,
    [UserRole.EMPLOYEE]: UserProfile.EMPLOYEE,
    [UserRole.USER]: UserProfile.ENTREPRENEUR,
    [UserRole.EXPERT_COMPTABLE]: UserProfile.EXPERT_COMPTABLE, // ✅ AJOUTER
    [UserRole.BANQUE]: UserProfile.BANQUE,                     // ✅ AJOUTER
  };
  
  const profile = roleToProfile[role] || UserProfile.ENTREPRENEUR;
  return PROFILE_MODULES[profile];
};
